public with sharing class LPLAN_Constants {
    public final static String ACCOUNT_SALESREP_READ_ROLE = 'Sales Representatives Read';
    public final static String ACCOUNT_SALESREP_EDIT_ROLE = 'Sales Representatives Edit';
    public final static String READ_ACCESS = 'Read';
    public final static String EDIT_ACCESS = 'Edit';
    public final static String SALES_REP_ROLE = 'SalesRepresentatives';
}
